services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CREATE_TOPICS: "raw.events:1:1,anomalies:1:1"
      CLUSTER_ID: "Mk3UOEB5T-6L5g-34qjA9Q"
    ports:
      - "9092:9092"
    networks:
      - anomaly-net
    healthcheck:
      test: [ "CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      INFLUXDB_DB: metrics
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
    ports:
      - "8086:8086"
    networks:
      - anomaly-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - anomaly-net
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  generator:
    build:
      context: .
      dockerfile: generator/Dockerfile
    container_name: generator
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      HMAC_SECRET: ${HMAC_SECRET}
    networks:
      - anomaly-net
    restart: on-failure

  detector:
    build:
      context: .
      dockerfile: detector/Dockerfile
    container_name: detector
    depends_on:
      - kafka
      - influxdb
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      HMAC_SECRET: ${HMAC_SECRET}
    networks:
      - anomaly-net
    restart: on-failure

  alerter:
    build:
      context: .
      dockerfile: alerter/Dockerfile
    container_name: alerter
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      HMAC_SECRET: ${HMAC_SECRET}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    networks:
      - anomaly-net
    restart: on-failure

networks:
  anomaly-net:
    driver: bridge